version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Xms256m -Xmx512m"
    depends_on:
      - postgres-1
      - mysql
      - postgres-2
    networks:
      - backend

  postgres-1:
    image: postgres:latest
    container_name: postgres-db-1
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    networks:
      - backend

  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  postgres-2:
    image: postgres:latest
    container_name: postgres-db-2
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data1:
  postgres_data2:
  mysql_data:
